tinyMCE.addI18n('br.xhtmlxtras_dlg',{
attribute_label_title:"T\u00C3\u0083\u00C2\u00ADtulo",
attribute_label_id:"ID",
attribute_label_class:"Classe",
attribute_label_style:"Estilo",
attribute_label_cite:"Citar",
attribute_label_datetime:"Data/Hora",
attribute_label_langdir:"Direc\u00C3\u0083\u00C2\u00A7\u00C3\u0083\u00C2\u00A3o do texto",
attribute_option_ltr:"Da esquerda para a direita",
attribute_option_rtl:"Da direita para esquerda",
attribute_label_langcode:"Linguagem",
attribute_label_tabindex:"TabIndex",
attribute_label_accesskey:"Chave de accesso",
attribute_events_tab:"Eventos",
attribute_attrib_tab:"Atributos",
general_tab:"Geral",
attrib_tab:"Atributos",
events_tab:"Eventos",
fieldset_general_tab:"Configura\u00C3\u0083\u00C2\u00A7\u00C3\u0083\u00C2\u00B5es gerais",
fieldset_attrib_tab:"Atributos",
fieldset_events_tab:"Eventos",
title_ins_element:"Inserir",
title_del_element:"Apagar",
title_acronym_element:"Acr\u00C3\u0083\u00C2\u00B4nimo",
title_abbr_element:"Abrevia\u00C3\u0083\u00C2\u00A7\u00C3\u0083\u00C2\u00A3o",
title_cite_element:"Cita\u00C3\u0083\u00C2\u00A7\u00C3\u0083\u00C2\u00A3o",
remove:"Remover",
insert_date:"Inserir data/hora",
option_ltr:"Da esquerda para a direita",
option_rtl:"Da direita para a esquerda",
attribs_title:"Inserir/editar atributos"
});