<?php
/*
 **************************************************************************
 *
 * OpenSRS-PHP
 *
 * Copyright (C) 2000, 2001, 2002, 2003 Colin Viebrock 
 *   and easyDNS Technologies Inc.
 *
 **************************************************************************
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 **************************************************************************
 *
 * vim: set expandtab tabstop=4 shiftwidth=4:
 * $Id: country_codes.php,v 1.1 2004/09/30 09:25:23 Tony Exp $
 *
 **************************************************************************
 */

$COUNTRY_CODES = array(
	'ac'	=> 'Ascension',
	'ad'	=> 'Andorra',
	'ae'	=> 'United Arab Emirates',
	'af'	=> 'Afghanistan',
	'ag'	=> 'Antigua and Barbuda',
	'ai'	=> 'Anguilla',
	'al'	=> 'Albania',
	'am'	=> 'Armenia',
	'an'	=> 'Netherland Antilles',
	'ao'	=> 'Angola',
	'aq'	=> 'Antarctica',
	'ar'	=> 'Argentina',
	'as'	=> 'American Samoa',
	'at'	=> 'Austria',
	'au'	=> 'Australia',
	'aw'	=> 'Aruba',
	'az'	=> 'Azerbaidjan',
	'ba'	=> 'Bosnia-Herzegovina',
	'bb'	=> 'Barbados',
	'bd'	=> 'Banglades',
	'be'	=> 'Belgium',
	'bf'	=> 'Burkina Faso',
	'bg'	=> 'Bulgaria',
	'bh'	=> 'Bahrain',
	'bi'	=> 'Burundi',
	'bj'	=> 'Benin',
	'bm'	=> 'Bermuda',
	'bn'	=> 'Brunei Darussalam',
	'bo'	=> 'Bolivia',
	'br'	=> 'Brazil',
	'bs'	=> 'Bahamas',
	'bt'	=> 'Buthan',
	'bv'	=> 'Bouvet Island',
	'bw'	=> 'Botswana',
	'by'	=> 'Belarus',
	'bz'	=> 'Belize',
	'ca'	=> 'Canada',
	'cc'	=> 'Cocos (Keeling) Islands',
	'cf'	=> 'Central African Republic',
	'cg'	=> 'Congo',
	'ch'	=> 'Switzerland',
	'ci'	=> 'Ivory Coast',
	'ck'	=> 'Cook Islands',
	'cl'	=> 'Chile',
	'cm'	=> 'Cameroon',
	'cn'	=> 'China',
	'co'	=> 'Colombia',
	'cr'	=> 'Costa Rica',
	'cs'	=> 'Czechoslovakia',
	'cu'	=> 'Cuba',
	'cv'	=> 'Cape Verde',
	'cx'	=> 'Christmas Island',
	'cy'	=> 'Cyprus',
	'cz'	=> 'Czech Republic',
	'de'	=> 'Germany',
	'dj'	=> 'Djibouti',
	'dk'	=> 'Denmark',
	'dm'	=> 'Dominica',
	'do'	=> 'Dominican Republic',
	'dz'	=> 'Algeria',
	'ec'	=> 'Ecuador',
	'ee'	=> 'Estonia',
	'eg'	=> 'Egypt',
	'eh'	=> 'Western Sahara',
	'es'	=> 'Spain',
	'et'	=> 'Ethiopia',
	'fi'	=> 'Finland',
	'fj'	=> 'Fiji',
	'fk'	=> 'Falkland Islands (Malvinas)',
	'fm'	=> 'Micronesia',
	'fo'	=> 'Faroe Islands',
	'fr'	=> 'France',
#	'fx'	=> 'France (European Territory)',
	'ga'	=> 'Gabon',
	'gb'	=> 'Great Britain',
	'gd'	=> 'Grenada',
	'ge'	=> 'Georgia',
	'gh'	=> 'Ghana',
	'gi'	=> 'Gibraltar',
	'gl'	=> 'Greenland',
	'gp'	=> 'Guadeloupe (French)',
	'gq'	=> 'Equatorial Guinea',
	'gf'	=> 'Guyana (French)',
	'gm'	=> 'Gambia',
	'gn'	=> 'Guinea',
	'gr'	=> 'Greece',
	'gs'	=> 'South Georgia and South Sandwich Islands',
	'gt'	=> 'Guatemala',
	'gu'	=> 'Guam (US)',
	'gw'	=> 'Guinea Bissau',
	'gy'	=> 'Guyana',
	'hk'	=> 'Hong Kong',
	'hm'	=> 'Heard and McDonald Islands',
	'hn'	=> 'Honduras',
	'hr'	=> 'Croatia',
	'ht'	=> 'Haiti',
	'hu'	=> 'Hungary',
	'id'	=> 'Indonesia',
	'ie'	=> 'Ireland',
	'il'	=> 'Israel',
	'in'	=> 'India',
	'io'	=> 'British Indian Ocean Territory',
	'iq'	=> 'Iraq',
	'ir'	=> 'Iran',
	'is'	=> 'Iceland',
	'it'	=> 'Italy',
	'jm'	=> 'Jamaica',
	'jo'	=> 'Jordan',
	'jp'	=> 'Japan',
	'ke'	=> 'Kenya',
	'kg'	=> 'Kirgistan',
	'kh'	=> 'Cambodia',
	'ki'	=> 'Kiribati',
	'km'	=> 'Comoros',
	'kn'	=> 'Saint Kitts Nevis Anguilla',
	'kp'	=> 'North Korea',
	'kr'	=> 'South Korea',
	'kw'	=> 'Kuwait',
	'ky'	=> 'Cayman Islands',
	'kz'	=> 'Kazachstan',
	'la'	=> 'Laos',
	'lb'	=> 'Lebanon',
	'lc'	=> 'Saint Lucia',
	'li'	=> 'Liechtenstein',
	'lk'	=> 'Sri Lanka',
	'lr'	=> 'Liberia',
	'ls'	=> 'Lesotho',
	'lt'	=> 'Lithuania',
	'lu'	=> 'Luxembourg',
	'lv'	=> 'Latvia',
	'ly'	=> 'Libya',
	'ma'	=> 'Morocco',
	'mc'	=> 'Monaco',
	'md'	=> 'Moldavia',
	'mg'	=> 'Madagascar',
	'mh'	=> 'Marshall Islands',
	'ml'	=> 'Mali',
	'mm'	=> 'Myanmar',
	'mn'	=> 'Mongolia',
	'mo'	=> 'Macau',
	'mp'	=> 'Northern Mariana Islands',
	'mq'	=> 'Martinique (French)',
	'mr'	=> 'Mauritania',
	'ms'	=> 'Montserrat',
	'mt'	=> 'Malta',
	'mu'	=> 'Mauritius',
	'mv'	=> 'Maldives',
	'mw'	=> 'Malawi',
	'mx'	=> 'Mexico',
	'my'	=> 'Malaysia',
	'mz'	=> 'Mozambique',
	'na'	=> 'Namibia',
	'nc'	=> 'New Caledonia (French)',
	'ne'	=> 'Niger',
	'nf'	=> 'Norfolk Island',
	'ng'	=> 'Nigeria',
	'ni'	=> 'Nicaragua',
	'nl'	=> 'Netherlands',
	'no'	=> 'Norway',
	'np'	=> 'Nepal',
	'nr'	=> 'Nauru',
	'nt'	=> 'Neutral Zone',
	'nu'	=> 'Niue',
	'nz'	=> 'New Zealand',
	'om'	=> 'Oman',
	'pa'	=> 'Panama',
	'pe'	=> 'Peru',
	'pf'	=> 'Polynesia (French)',
	'pg'	=> 'Papua New',
	'ph'	=> 'Philippines',
	'pk'	=> 'Pakistan',
	'pl'	=> 'Poland',
	'pm'	=> 'Saint Pierre and Miquelon',
	'pn'	=> 'Pitcairn',
	'pt'	=> 'Portugal',
	'pr'	=> 'Puerto Rico (US)',
	'pw'	=> 'Palau',
	'py'	=> 'Paraguay',
	'qa'	=> 'Qatar',
	're'	=> 'Reunion (French)',
	'ro'	=> 'Romania',
	'ru'	=> 'Russian Federation',
	'rw'	=> 'Rwanda',
	'sa'	=> 'Saudi Arabia',
	'sb'	=> 'Solomon Islands',
	'sc'	=> 'Seychelles',
	'sd'	=> 'Sudan',
	'se'	=> 'Sweden',
	'sg'	=> 'Singapore',
	'sh'	=> 'Saint Helena',
	'si'	=> 'Slovenia',
	'sj'	=> 'Svalbard and Jan Mayen Islands',
	'sk'	=> 'Slovak Republic',
	'sl'	=> 'Sierra Leone',
	'sm'	=> 'San Marino',
	'sn'	=> 'Senegal',
	'so'	=> 'Somalia',
	'sr'	=> 'Suriname',
	'st'	=> 'Saint Tome and Principe',
	'su'	=> 'Soviet Union',
	'sv'	=> 'El Salvador',
	'sy'	=> 'Syria',
	'sz'	=> 'Swaziland',
	'tc'	=> 'Turks and Caicos Islands',
	'td'	=> 'Chad',
	'tf'	=> 'French Southern Territory',
	'tg'	=> 'Togo',
	'th'	=> 'Thailand',
	'tj'	=> 'Tadjikistan',
	'tk'	=> 'Tokelau',
	'tm'	=> 'Turkmenistan',
	'tn'	=> 'Tunisia',
	'to'	=> 'Tonga',
	'tp'	=> 'East Timor',
	'tr'	=> 'Turkey',
	'tt'	=> 'Trinidad and Tobago',
	'tv'	=> 'Tuvalu',
	'tw'	=> 'Taiwan',
	'tz'	=> 'Tanzania',
	'ua'	=> 'Ukraine',
	'ug'	=> 'Uganda',
	'uk'	=> 'United Kingdom',
	'um'	=> 'US Minor Outlying Islands',
	'us'	=> 'United States',
	'uy'	=> 'Uruguay',
	'uz'	=> 'Uzbekistan',
	'va'	=> 'Vatican City State',
	'vc'	=> 'Saint Vincent and Grenadines',
	've'	=> 'Venezuela',
	'vg'	=> 'Virgin Islands (British)',
	'vi'	=> 'Virgin Islands (US)',
	'vn'	=> 'Vietnam',
	'vu'	=> 'Vanuatu',
	'wf'	=> 'Wallis and Futuna Islands',
	'ws'	=> 'Samoa',
	'ye'	=> 'Yemen',
	'yu'	=> 'Yugoslavia',
	'za'	=> 'South Africa',
	'zm'	=> 'Zambia',
	'zr'	=> 'Zaire',
	'zw'	=> 'Zimbabwe',
);


