#!/usr/bin/python

import sys
import posix
import os

posix.system('/usr/sbin/retrieve_sip_conf_from_mysql.pl')
a = posix.system('diff -q /etc/asterisk/sip_agilevoice.conf.tmp /etc/asterisk/sip_agilevoice.conf >/dev/null 2>&1')
if a:
	try:
		os.unlink('/etc/asterisk/sip_agilevoice.conf')
	except OSError:
		pass
	posix.system('mv -f /etc/asterisk/sip_agilevoice.conf.tmp /etc/asterisk/sip_agilevoice.conf')
	posix.system('asterisk -rx "sip reload" >/dev/null 2>&1')
	posix.system('asterisk -rx "reload app_voicemail.so" >/dev/null 2>&1')

